version: 2
jobs:
  build:
    working_directory: /go/src/s32x.com/ovrstat
    environment:
      - DOCKER_TAG: s32x/ovrstat
    docker:
      - image: circleci/golang:1.11.3
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: make test
      - run:
          name: Build binary for Alpine linux
          command: env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/server
      - setup_remote_docker
      - run:
          name: Build Docker image with binary
          command: docker build --no-cache -t $DOCKER_TAG .
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Push image to DockerHub
          command: docker push $DOCKER_TAG